name = "kimi-cloudflare"
main = "index.js"
compatibility_date = "2026-06-25"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "CONVERSATIONS"
id = "794e0c7f29854069885dab4508629b04"

[observability.logs]
enabled = true
invocation_logs = true

