name = "kimi-cloudflare"
main = "index.js"
compatibility_date = "2026-06-25"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "CONVERSATIONS"
id = "95084f10418f44e48b0cef53ffca5fab"

[observability.logs]
enabled = true
invocation_logs = true

